all:
	@for i in TL TR BR BL T R B L; do \
		ln -sf frameA$$i.xpm frameI$$i.xpm; \
		ln -sf dframeA$$i.xpm dframeI$$i.xpm; \
	done

	@for i in AT AR AB AL IT IR IB IL; do \
		ln -sf frame$$i.xpm dframe$$i.xpm; \
	done
