#!/bin/sh

SHELL=/bin/sh
export SHELL

# Load key mapping
xmodmap /usr/X11R6/Xmodmap

# Load x resources
xrdb -nocpp -merge /usr/X11R6/Xresources

for i in /usr/X11R6/lib/X11/fonts/* ; do
  [ -d $i ] && xset +fp $i
done

while true ; do /usr/X11R6/sbin/init ; done
