#!/bin/sh
# /etc/ppp/ipup
#  Creates /etc/resolv.conf and adds DNS entries to it so
#  so you can get out and do something useful on the net.

if [ -n "$DNS1" ] ; then 
	echo "" > /etc/resolv.conf
	echo "nameserver $DNS1" >> /etc/resolv.conf
	if [ -n "$DNS2" ] ; then
		echo "nameserver $DNS2" >> /etc/resolv.conf
	 fi
fi
